class Animal {
  final int? id;
  final int farmer;
  final String? farmerUsername; // Farmer's username for display
  final String species;
  final int age;
  final double weight;
  final DateTime createdAt;
  final bool slaughtered;
  final DateTime? slaughteredAt;
  final String animalId; // Auto-generated unique identifier
  final String? animalName; // Optional user-friendly name/tag
  final String? breed;
  final String farmName;
  final String? healthStatus;
  final bool synced;
  // Transfer fields
  final int? transferredTo;
  final DateTime? transferredAt;
  // Receive fields
  final int? receivedBy;
  final DateTime? receivedAt;

  Animal({
    this.id,
    required this.farmer,
    this.farmerUsername,
    required this.species,
    required this.age,
    required this.weight,
    required this.createdAt,
    required this.slaughtered,
    this.slaughteredAt,
    required this.animalId,
    this.animalName,
    this.breed,
    required this.farmName,
    this.healthStatus,
    this.synced = true,
    this.transferredTo,
    this.transferredAt,
    this.receivedBy,
    this.receivedAt,
  });

  factory Animal.fromMap(Map<String, dynamic> json) {
    return Animal(
      id: json['id'] != null ? int.parse(json['id'].toString()) : null,
      farmer: int.parse(json['farmer'].toString()),
      farmerUsername: json['farmer_username'],
      species: json['species'],
      age: json['age'] is int ? json['age'] : int.parse(json['age'].toString()),
      weight: json['weight'] is num ? (json['weight'] as num).toDouble() : double.parse(json['weight'].toString()),
      createdAt: DateTime.parse(json['created_at']),
      slaughtered: json['slaughtered'],
      slaughteredAt: json['slaughtered_at'] != null
          ? DateTime.parse(json['slaughtered_at'])
          : null,
      animalId: json['animal_id'],
      animalName: json['animal_name'],
      breed: json['breed'],
      farmName: json['farm_name'],
      healthStatus: json['health_status'],
      synced: json['synced'] ?? true,
      transferredTo: json['transferred_to'] != null ? int.parse(json['transferred_to'].toString()) : null,
      transferredAt: json['transferred_at'] != null
          ? DateTime.parse(json['transferred_at'])
          : null,
      receivedBy: json['received_by'] != null ? int.parse(json['received_by'].toString()) : null,
      receivedAt: json['received_at'] != null
          ? DateTime.parse(json['received_at'])
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'farmer': farmer,
      'farmer_username': farmerUsername,
      'species': species,
      'age': age,
      'weight': weight,
      'created_at': createdAt.toIso8601String(),
      'slaughtered': slaughtered,
      'slaughtered_at': slaughteredAt?.toIso8601String(),
      'animal_id': animalId,
      'animal_name': animalName,
      'breed': breed,
      'farm_name': farmName,
      'health_status': healthStatus,
      'synced': synced,
      'transferred_to': transferredTo,
      'transferred_at': transferredAt?.toIso8601String(),
      'received_by': receivedBy,
      'received_at': receivedAt?.toIso8601String(),
    };
  }

  // For creating new animal (exclude id and auto-generated fields)
  Map<String, dynamic> toMapForCreate() {
    return {
      'species': species.toLowerCase(), // Convert to lowercase to match backend choices
      'age': age,
      'weight': weight,
      'animal_name': animalName, // Optional user-friendly name
      'breed': breed,
      'farm_name': farmName,
      'health_status': healthStatus,
      // Note: animal_id is auto-generated by backend, farmer is set automatically from authenticated user
    };
  }
}
