class Animal {
  final int? id;
  final int farmer;
  final String species;
  final int age;
  final double weight;
  final DateTime createdAt;
  final bool slaughtered;
  final DateTime? slaughteredAt;
  final String animalId; // Auto-generated unique identifier
  final String? animalName; // Optional user-friendly name/tag
  final String? breed;
  final String farmName;
  final String? healthStatus;
  final bool synced;

  Animal({
    this.id,
    required this.farmer,
    required this.species,
    required this.age,
    required this.weight,
    required this.createdAt,
    required this.slaughtered,
    this.slaughteredAt,
    required this.animalId,
    this.animalName,
    this.breed,
    required this.farmName,
    this.healthStatus,
    this.synced = true,
  });

  factory Animal.fromMap(Map<String, dynamic> json) {
    return Animal(
      id: json['id'] != null ? int.parse(json['id'].toString()) : null,
      farmer: int.parse(json['farmer'].toString()),
      species: json['species'],
      age: json['age'] is int ? json['age'] : int.parse(json['age'].toString()),
      weight: json['weight'] is num ? (json['weight'] as num).toDouble() : double.parse(json['weight'].toString()),
      createdAt: DateTime.parse(json['created_at']),
      slaughtered: json['slaughtered'],
      slaughteredAt: json['slaughtered_at'] != null
          ? DateTime.parse(json['slaughtered_at'])
          : null,
      animalId: json['animal_id'],
      animalName: json['animal_name'],
      breed: json['breed'],
      farmName: json['farm_name'],
      healthStatus: json['health_status'],
      synced: json['synced'] ?? true,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'farmer': farmer,
      'species': species,
      'age': age,
      'weight': weight,
      'created_at': createdAt.toIso8601String(),
      'slaughtered': slaughtered,
      'slaughtered_at': slaughteredAt?.toIso8601String(),
      'animal_id': animalId,
      'animal_name': animalName,
      'breed': breed,
      'farm_name': farmName,
      'health_status': healthStatus,
      'synced': synced,
    };
  }

  // For creating new animal (exclude id and auto-generated fields)
  Map<String, dynamic> toMapForCreate() {
    return {
      'species': species.toLowerCase(), // Convert to lowercase to match backend choices
      'age': age,
      'weight': weight,
      'animal_name': animalName, // Optional user-friendly name
      'breed': breed,
      'farm_name': farmName,
      'health_status': healthStatus,
      // Note: animal_id is auto-generated by backend, farmer is set automatically from authenticated user
    };
  }
}
