class Waste {
  final int? id;
  final int? animal;
  final String? animalId;
  final String? animalSpecies;
  final int? slaughterPart;
  final int? product;
  final String wasteType;
  final String stage;
  final double weightKg;
  final double? expectedWeightKg;
  final double? actualWeightKg;
  final bool autoGenerated;
  final String? notes;
  final int? recordedBy;
  final int? abbatoir;
  final int? processingUnit;
  final DateTime recordedAt;

  Waste({
    this.id,
    this.animal,
    this.animalId,
    this.animalSpecies,
    this.slaughterPart,
    this.product,
    required this.wasteType,
    this.stage = 'abbatoir',
    required this.weightKg,
    this.expectedWeightKg,
    this.actualWeightKg,
    this.autoGenerated = false,
    this.notes,
    this.recordedBy,
    this.abbatoir,
    this.processingUnit,
    required this.recordedAt,
  });

  factory Waste.fromJson(Map<String, dynamic> json) {
    return Waste(
      id: json['id'],
      animal: json['animal'],
      animalId: json['animal_id'],
      animalSpecies: json['animal_species'],
      slaughterPart: json['slaughter_part'],
      product: json['product'],
      wasteType: json['waste_type'] ?? 'other',
      stage: json['stage'] ?? 'abbatoir',
      weightKg: (json['weight_kg'] as num?)?.toDouble() ?? 0.0,
      expectedWeightKg: (json['expected_weight_kg'] as num?)?.toDouble(),
      actualWeightKg: (json['actual_weight_kg'] as num?)?.toDouble(),
      autoGenerated: json['auto_generated'] ?? false,
      notes: json['notes'],
      recordedBy: json['recorded_by'],
      abbatoir: json['abbatoir'],
      processingUnit: json['processing_unit'],
      recordedAt: json['recorded_at'] != null
          ? DateTime.parse(json['recorded_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'animal': animal,
      'waste_type': wasteType,
      'stage': stage,
      'weight_kg': weightKg,
      'expected_weight_kg': expectedWeightKg,
      'actual_weight_kg': actualWeightKg,
      'auto_generated': autoGenerated,
      'notes': notes,
      'recorded_by': recordedBy,
      'abbatoir': abbatoir,
      'processing_unit': processingUnit,
      'recorded_at': recordedAt.toIso8601String(),
    };
  }

  String get wasteTypeDisplay {
    switch (wasteType) {
      case 'evisceration':
        return 'Evisceration Loss';
      case 'processing':
        return 'Processing Loss';
      case 'rejection':
        return 'Rejection Loss';
      case 'trimming':
        return 'Trimming Loss';
      case 'spoilage':
        return 'Spoilage';
      case 'other':
        return 'Other';
      default:
        return wasteType;
    }
  }

  String get stageDisplay {
    switch (stage) {
      case 'abbatoir':
        return 'Abbatoir';
      case 'processing_unit':
        return 'Processing Unit';
      case 'shop':
        return 'Shop';
      default:
        return stage;
    }
  }
}
